<section class="add-category-form-container">
    <h2>Agregar Categoría</h2>
    <form method="POST" action="add_category_process.php">

        <label for="category_name">Nombre de la Categoría:</label>
        <input type="text" id="category_name" name="category_name" placeholder="Nombre de la categoría" required>

        <input type="submit" value="Agregar Categoría">
    </form>
</section>
