<section>
    <form id="loginForm" method="POST">

        <label for="username">Usuario:</label>
        <input type="text" id="username" name="username" placeholder="Nombre de usuario" required>

        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" placeholder="Contraseña" required>

        <p id="errorMessage"><?php echo $error; ?></p>

        <input type="submit" value="Iniciar sesión">

        <p> o </p>

        <input type="button" value="Registrarse" onclick="location.href='index.php?action=register'">
    </form>
</section>

<script src="js/login.js"></script>