<div class="nav-container-container">
    <div class="nav-container">
        <div class="btn-menu">
            <a>
                <svg width="50px" height="50px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="#ffffff" stroke="#ffffff" stroke-width="0.00024000000000000003"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M3 5h18v1H3zm0 8h18v-1H3zm0 7h18v-1H3z"></path><path fill="none" d="M0 0h24v24H0z"></path></g></svg>
            </a>
        </div>
        <div class="logo-container-home">
            <a href="home.php">
                <img src="images/logo_white.png" class="logo-white" alt="Logo">
            </a>
        </div>
        <div class="btn-shop">
            <a>
                <svg width="50px" height="50px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="#ffffff" stroke="#ffffff" stroke-width="0.00024000000000000003"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M6.787 15.981l14.11-1.008L23.141 6H5.345L5.06 4.37a1.51 1.51 0 0 0-1.307-1.23l-2.496-.286-.114.994 2.497.286a.502.502 0 0 1 .435.41l1.9 10.853-.826 1.301A1.497 1.497 0 0 0 6 18.94v.153a1.5 1.5 0 1 0 1 0V19h11.5a.497.497 0 0 1 .356.15 1.502 1.502 0 1 0 1.074-.08A1.497 1.497 0 0 0 18.5 18H6.416a.5.5 0 0 1-.422-.768zM19.5 21a.5.5 0 1 1 .5-.5.5.5 0 0 1-.5.5zm-13 0a.5.5 0 1 1 .5-.5.5.5 0 0 1-.5.5zM21.86 7l-1.757 7.027-13.188.942L5.52 7z"></path><path fill="none" d="M0 0h24v24H0z"></path></g></svg>
            </a>
        </div>
    </div>

    <nav class="navigation-container">
    <ul class="navigation">
        <li><a href="home.php">Home</a></li>
        <li><a href="clasicas.php">Clásicas</a></li>
        <li><a href="especiales.php">Especiales</a></li>
        <?php if (isset($_SESSION['is_admin']) && $_SESSION['is_admin']): ?>
            <li><a href="admin.php">Admin</a></li>
        <?php endif; ?>
        <li><span id="logout">Cerrar sesión</span></li>
    </ul>
</nav>

    <div class="shop-container">
        <div class="shop" id="shop">
        <div id="cart-products-container"></div>
        <p class="total" id="cart-total">Total: $0</p>
        <p id="finish-button">Finalizar compra</p>
        <p id="cancel-button">Cancelar</p>
    </div>



    <script src="js/logout.js"></script>
    <script src="js/nav.js"></script>
</div>
