<h1 class="category-title"><?php echo htmlspecialchars($categoryTitle); ?></h1>
        <section class="pizzas-category">
            <?php
            if ($result->num_rows > 0) {
                while ($row = $result->fetch_assoc()) {
                    echo '<div class="card">';
                    echo '<img src="images/' . htmlspecialchars($row['image']) . '" alt="' . htmlspecialchars($row['pizza_name']) . '">';
                    echo '<div class="card-content">';
                    echo '<div class="pizza-info">';
                    echo '<h3>' . htmlspecialchars($row['pizza_name']) . '</h3>';
                    echo '<p class="price">$' . htmlspecialchars($row['price']) . '</p>';
                    echo '</div>';
                    echo '<button class="add-cart" data-id="' . $row['pizza_id'] . '" data-price="' . $row['price'] . '">
                            <svg width="50px" height="50px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="#ffffff" stroke="#ffffff" stroke-width="0.00024000000000000003">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <path d="M12.5 2.2a10.3 10.3 0 1 0 10.3 10.3A10.299 10.299 0 0 0 12.5 2.2zm0 19.6a9.3 9.3 0 1 1 9.3-9.3 9.31 9.31 0 0 1-9.3 9.3zM13 12h5v1h-5v5h-1v-5H7v-1h5V7h1z"></path>
                                    <path fill="none" d="M0 0h24v24H0z"></path>
                                </g>
                            </svg>
                          </button>';
                    echo '</div>'; 
                    echo '</div>'; 
                }
            } else {
                echo '<p>No hay pizzas especiales disponibles.</p>';
            }
            ?>
</section>