<div class="promos">
    <div class="promo-container">
        <img class="promo-image" src="images/promo_1.png" alt="Promoción 1">
        <img class="promo-image" src="images/promo_2.png" alt="Promoción 2" style="opacity: 0;">
        <img class="promo-image" src="images/promo_3.png" alt="Promoción 3" style="opacity: 0;">
    </div>
</div>
<h1 class="welcome">Bienvenidx, <span class="name-color"><?php echo $_SESSION['username']; ?></span>!</h1>